In [2]:
import tensorflow as tf
tf.__version__;

### Constant

In [3]:
hello = tf.constant("Hello")
world = tf.constant("World")

In [4]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [5]:
hello

<tf.Tensor 'Const:0' shape=() dtype=string>

"with" automatically opens and close the session

### Session

In [11]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [12]:
print(result)

b'HelloWorld'


In [13]:
a = tf.constant(10)
b = tf.constant(20)

In [14]:
type(a)

tensorflow.python.framework.ops.Tensor

In [15]:
a + b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [16]:
a + b

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [17]:
with tf.Session() as sess:
    result = sess.run(a+b)
    
result

30

In [18]:
const = tf.constant(10)

In [38]:
fill_mat = tf.fill([3,3],99)

In [21]:
my_zeros = tf.zeros([2,3])
my_ones = tf.ones([3,2])

In [22]:
my_randn =  tf.random_normal([3,2],mean=2,stddev=1)
my_randu = tf.random_uniform([3,3],minval=1,maxval=5)

In [39]:
my_ops = [const,fill_mat,my_zeros,my_ones,my_randn,my_randu]

## InteractiveSession

In [42]:
sess = tf.InteractiveSession()

/home/hdsingh/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py:1711: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


#### Run

In [41]:
for op in my_ops:
    print(sess.run(op))
    print('\n')

10


[[99 99 99]
 [99 99 99]
 [99 99 99]]


[[0. 0. 0.]
 [0. 0. 0.]]


[[1. 1.]
 [1. 1.]
 [1. 1.]]


[[ 1.2407546  -0.98132515]
 [ 3.3636384   0.78018653]
 [ 3.979353    3.6554737 ]]


[[4.2036915 2.6582327 3.2594829]
 [4.3297386 2.3008614 3.844779 ]
 [2.9267998 2.8035927 1.695962 ]]




#### Eval

In [43]:
for op in my_ops:
    print(op.eval())
    print('\n')

10


[[99 99 99]
 [99 99 99]
 [99 99 99]]


[[0. 0. 0.]
 [0. 0. 0.]]


[[1. 1.]
 [1. 1.]
 [1. 1.]]


[[2.3410172 2.7728434]
 [2.0787156 0.8896997]
 [2.9638953 2.0825446]]


[[4.074883  2.6282392 3.2372308]
 [1.9702635 2.9382935 2.6759534]
 [4.4773107 4.4016976 1.3158269]]




### Matrix Mul

In [45]:
a = tf.constant([[1,2],
                [3,4]])

In [46]:
a.shape

TensorShape([Dimension(2), Dimension(2)])

In [47]:
b = tf.constant([ [10], [100]])
result = tf.matmul(a,b)

In [48]:
sess.run(result)

array([[210],
       [430]], dtype=int32)

In [ ]:
print